en = {
  "embed_commands_dict": {
    "mob": "mot",
    "playbooks": "playbooks"
  },
  "generic_playbook_dict": {
    "lock": "lock",
    "editlabels": "editlabels",
    "potential": "potential",
    "removepotential": "removepotential",
    "markcondition": "markcondition",
    "clearcondition": "clearcondition",
    "create": "create",
    "labels": "labels",
    "conditions": "conditions",
    "get_potential": "get_potential",
    "pending_advancements": "pending_advancements",
    "advancements": "advancements",
    "print": "print",
    "deletecharacter": "deletecharacter",
    "replicate": "replicate",
    "el": "editlabels",
    "cc": "clearcondition",
    "mc": "markcondition"
  },
  "settings_dict": {
    "helphere": "helphere",
    "settings": "settings",
    "changesettings": "change_settings",
    "language": "language",
    "teamname": "teamname",
    "dicedisplay": "dicedisplay",
    "updatelang": "update_lang",
    "updategm": "update_gm",
    "updateteamname": "update_teamname",
    "createsettings": "create_settings",
    "deletesettings": "delete_settings",
    "team": "add_team",
    "spend": "spend_team",
    "pool": "check_team",
    "empty": "empty_team",
    "dicetoggle": "toggle_dice"
  },
  "generic_advancements_dict": {
    "mov_my_playbook": "mov_my_playbook",
    "mov_other_playbook": "mov_other_playbook",
    "rearrange": "rearrange"
  },
  "playbook_specific_advancements_dict": {
    "more_roles": "more_roles",
    "add_adult": "add_adult",
    "more_to_labels": "more_to_labels",
    "clear_sign": "clear_sign",
    "mark_sign": "mark_sign",
    "get_burns": "get_burns",
    "mask_label": "mask_label",
    "get_drives": "get_drives",
    "get_sanctuary": "get_sanctuary",
    "more_flares": "more_flares",
    "get_heart": "get_heart",
    "get_mask": "get_mask",
    "mentor_label": "mentor_label",
    "more_resources": "more_resources",
    "get_mentor": "get_mentor",
    "get_legacy": "get_legacy",
    "lock_soldier": "lock_soldier"
  },
  "dice_rolling": {
    "calculation_title": "Calculation",
    "calculation": lambda result1, result2, mod, calc: f"Dice **{result1}** + **{result2}**, Modifier {mod} **{calc}**",
    "dice": "Dice",
    "label": lambda label_name, label_value: f"**{label_name}** is **{label_value}**\n",
    "result": "Result",
    "condition_text": lambda condition, name: f"-2 as **{name}** is **{condition}**!\n",
    "conditions_marked": lambda conditions, name: f"**{name}** has {conditions} conditions marked!\n",
    "command_modifier": lambda mod: f"Modifier from command is **{mod}**\n"
  },
  "description": "Description",
  "moves": {
    "moves": "moves",
    "adult": "adult",
    "non_existent_playbook_intro": "Sorry, I couldn't find that playbook, the available playbooks are:",
    "non_existent_playbook_end": "\nType an exclamation sign and one of the names in lowercase and without the 'The', moves or adult\ne.g.: !beacon, !moves, !adult",
    "moves_plus": {
      "response_header": "**Name - description, keyword, label**\n"
    }
  },
  "playbook_interactions": {
    "fail_preffix": "Oh no, ",
    "already_locked": lambda label_name: f"Oh no, {label_name} is already locked!",
    "is_locked": lambda label_name: f"Oh no, {label_name} is locked, this one can't change!",
    "labels_base": "Your labels are:\n",
    "up": "up",
    "down": "down",
    "value_is_in_border": lambda value, label_name, direction: f"Oh no, with a value of {value}, your {label_name} can't go {direction}! You get a condition!",
    "locked": "[LOCKED]",
    "condition_not_marked": "You don't have any condition marked",
    "youre": "You are:\n",
    "dont": "don't ",
    "condition_status": lambda status: f"Oh, you {status} have that condition marked.",
    "no_character": "I'm sorry but it appears you have no character created",
    "existing_character": "I'm sorry but it appears you already have character created in this channel",
    "invalid_condition": lambda condition_name: f"Oh no, {condition_name} is not a valid condition",
    "different_labels": "The labels must be different",
    "congrats_pending_advancements": lambda adv_count: f"Nice, you can now do {adv_count + 1} growth advancements",
    "congrats_potential": lambda potential: f"Nice, you have {potential} growth marked",
    "no_template": lambda playbook_name: f"It seems I don't have a template for a playbook called {playbook_name}",
    "congrats_on_creation": lambda char, playbook: f"Congratulations {char}, The {playbook} on joining the team!",
    "potential": lambda potential: f"You have {potential} growth marked",
    "nopotential": "Sorry, you have no growth potential marked",
    "basic": "\nBasic:",
    "advanced": "\nAdvanced:",
    "taken": "[TOMADO] ",
    "pending_advancements": lambda adv_count: f"You can do {adv_count} growth advancements",
    "no_moves_pb": "I'm sorry, but there are no moves from your playbook that match that name",
    "no_moves": "I'm sorry, but there are no moves that match that name",
    "move_already_taken": "You already have this move, choose another one",
    "successfully_added_move": lambda move_name: f"Nice, you can now use the move {move_name}",
    "your_playbook": "You can't add a move from your playbook with this advancement",
    "more": "more",
    "less": "less",
    "equal": "equal",
    "add_one_to_label": lambda difference, direction: f"You should add one to a label, the difference with these values has {difference} {direction} than the original sum",
    "less_than_min": lambda min_allowed, intended: f"I'm sorry, but {intended} is not a valid label value. The minimum is {min_allowed}",
    "greater_than_max": lambda max_allowed, intended: f"I'm sorry, but {intended} is not a valid label value. The maximum is {max_allowed}",
    "no_playbook": lambda name: f"To take this advancement you must have one of the following playbooks:{name}",
    "successfull_update": "The update was successfull",
    "already_max": lambda value, name: f"The {name} label already has the max value ({value})",
    "invalid_label": lambda name: f"The label {name} does not exist. ",
    "already_have": lambda name: f"You already have {name}",
    "character_deletion": lambda char, playbook: f"Goodbye {char}, the {playbook} - You have deleted your character in this channel.",
    "character_replication": lambda char, playbook: f"Successfully replicated {char}, the {playbook}.  This character now exists in 2 places at once."
  },
  "labels": {
    "creativity": "creativity",
    "focus": "focus",
    "harmony": "harmony",
    "passion": "passion",
    "principle": "principle"
  },
  "inverted_labels": {
    "creativity": "creativity",
    "focus": "focus",
    "harmony": "harmony",
    "passion": "passion",
    "principle": "principle"
  },
  "conditions": {
    "afraid": "afraid",
    "angry": "angry",
    "foolish": "foolish",
    "guilty": "guilty",
    "insecure": "insecure"
  },
  "inverted_conditions": {
    "afraid": "afraid",
    "angry": "angry",
    "foolish": "foolish",
    "guilty": "guilty",
    "insecure": "insecure"
  },
  "configuration": {
    "settings": "Settings\n",
    "language": "Language",
    "teamname": "Team name",
    "gm": "GM",
    "customNames": "Custom names",
    "dicetoggle": "Dice toggle",
    "no_file": "This chat doesn't have a configuration file. To create it write the following command:\n!createsettings en\nif you wish for it to be in english.\n",
    "existing_settings": "This chat already has a configuration file.",
    "successfull_update": "The update was successful",
    "successfull_creation": "The configuration file has been created",
    "successfull_deletion": "The configuration file has been deleted",
    "invalid_lang": lambda lang: f"{lang} is not a valid language, the options are: en (english), es (spanish)",
    "gm": "GM",
    #"team_pool": lambda team: f"You have {team} in the team pool",
    "team_pool": lambda team: f"You have {team} in the team pool",
    "insufficient_team": "You don't have enough team for that!",
    "dicedisplay": "dicedisplay",
    "dicedisplayswitched": lambda dice: f"Dice display toggled, currently set to {dice}"
  },
  "playbooks": {
    "the": "The",
    "list": ['bold', 'guardian', 'hammer', 'icon', 'idealist', 'successor'],
    "names": {
      "bold": "bold",
      "guardian": "guardian",
      "hammer": "hammer",
      "icon": "icon",
      "idealist": "idealist",
      "successor": "successor"
    },
    "inverted_names": {
      "bold": "bold",
      "guardian": "guardian",
      "hammer": "hammer",
      "icon": "icon",
      "idealist": "idealist",
      "successor": "successor"
    },
    "playbooks": "Playbooks",
    "available": "Available Playbooks are - ",
    "playbook_re": r"![a-z]+ ([a-z]+)",
    #"celebrate_re": r"!celebrate ([a-z]+)",
    #"weakness_re": r"!weakness ([a-z]+)",
    "moment_of_truth": "MOMENT OF TRUTH",
    "celebrate": "Triumphant Celebration",
    "weakness": "Vulnerability or Weakness",
    "this_is_mot": lambda usr: f"This is {usr}'s moment!",
    "this_is_celebrate": lambda usr: f"{usr} celebrates a triumph!",
    "this_is_weakness": lambda usr: f"{usr} opens up and shares!",
    "advances": {
      "moveYouPlaybook": "Take another move from your playbook",
      "moveOtherPlaybook": "Take a move from another playbook",
      "mot": "Unlock your Moment of Balance",
      "motAgain": "Unlock your Moment of Balance after it's been used once",
      "plusOne": "Add +1 to a label",
      "shiftCenter": "Shift your center one step",
      "shiftCenterAgain": "Shift your center one step",
    }

  }
}


def get_en_dict():
    return en